# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-gbcontainer-peg

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: crpeg1.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8D8DF9F95B9D4E7B82DC0951309DFD0B }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_9B1330ABD3FB4DE0A2D08881F6CF3072 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: crpeg1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8D8DF9F95B9D4E7B82DC0951309DFD0B }}/guestbook-app:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-gbcontainer-peg'
          slot-name: 'Production'
          images: 'crpeg1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8D8DF9F95B9D4E7B82DC0951309DFD0B }}/guestbook-app:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_60E10268ED3C4972B55806D53BA7A277 }}